services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # map localhost:3000 to Nginx container port 80
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
